apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-ui
  namespace: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-ui
  template:
    metadata:
      labels:
        app: netflix-ui
    spec:
      containers:
        - name: netflix-ui
          image: shradha91103/netflix-ui-clone:local
          ports:
            - containerPort: 3000

