apiVersion: v1
kind: Service
metadata:
  name: netflix-ui-service
  namespace: netflix
spec:
  selector:
    app: netflix-ui
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30033


